// The OpenIndex internal data plane. Every inter-process call in the engine is
// a gRPC method defined here; this file is the single source of truth for the
// wire format (impl spec 02.4). Domain logic converts these messages to the
// Go types it owns at its package edge - these types do not travel deep into
// scoring or merge code (impl spec 02.6).
//
// Compatibility rule: fields are added, never renumbered or repurposed; removed
// fields are reserved. The snapshot id and codec version travel in the request
// so a leaf can reject a format it cannot read instead of misreading it.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/openindex.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Leaf_Search_FullMethodName = "/openindex.v1.Leaf/Search"
)

// LeafClient is the client API for Leaf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeafClient interface {
	// Search scores one shard under the inherited deadline.
	Search(ctx context.Context, in *SearchShardReq, opts ...grpc.CallOption) (*SearchShardResp, error)
}

type leafClient struct {
	cc grpc.ClientConnInterface
}

func NewLeafClient(cc grpc.ClientConnInterface) LeafClient {
	return &leafClient{cc}
}

func (c *leafClient) Search(ctx context.Context, in *SearchShardReq, opts ...grpc.CallOption) (*SearchShardResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchShardResp)
	err := c.cc.Invoke(ctx, Leaf_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeafServer is the server API for Leaf service.
// All implementations must embed UnimplementedLeafServer
// for forward compatibility.
type LeafServer interface {
	// Search scores one shard under the inherited deadline.
	Search(context.Context, *SearchShardReq) (*SearchShardResp, error)
	mustEmbedUnimplementedLeafServer()
}

// UnimplementedLeafServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeafServer struct{}

func (UnimplementedLeafServer) Search(context.Context, *SearchShardReq) (*SearchShardResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedLeafServer) mustEmbedUnimplementedLeafServer() {}
func (UnimplementedLeafServer) testEmbeddedByValue()              {}

// UnsafeLeafServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeafServer will
// result in compilation errors.
type UnsafeLeafServer interface {
	mustEmbedUnimplementedLeafServer()
}

func RegisterLeafServer(s grpc.ServiceRegistrar, srv LeafServer) {
	// If the following call panics, it indicates UnimplementedLeafServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Leaf_ServiceDesc, srv)
}

func _Leaf_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchShardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeafServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Leaf_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeafServer).Search(ctx, req.(*SearchShardReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Leaf_ServiceDesc is the grpc.ServiceDesc for Leaf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Leaf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openindex.v1.Leaf",
	HandlerType: (*LeafServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Leaf_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/openindex.proto",
}

const (
	Aggregator_Search_FullMethodName = "/openindex.v1.Aggregator/Search"
)

// AggregatorClient is the client API for Aggregator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AggregatorClient interface {
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
}

type aggregatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregatorClient(cc grpc.ClientConnInterface) AggregatorClient {
	return &aggregatorClient{cc}
}

func (c *aggregatorClient) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, Aggregator_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregatorServer is the server API for Aggregator service.
// All implementations must embed UnimplementedAggregatorServer
// for forward compatibility.
type AggregatorServer interface {
	Search(context.Context, *SearchReq) (*SearchResp, error)
	mustEmbedUnimplementedAggregatorServer()
}

// UnimplementedAggregatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregatorServer struct{}

func (UnimplementedAggregatorServer) Search(context.Context, *SearchReq) (*SearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedAggregatorServer) mustEmbedUnimplementedAggregatorServer() {}
func (UnimplementedAggregatorServer) testEmbeddedByValue()                    {}

// UnsafeAggregatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregatorServer will
// result in compilation errors.
type UnsafeAggregatorServer interface {
	mustEmbedUnimplementedAggregatorServer()
}

func RegisterAggregatorServer(s grpc.ServiceRegistrar, srv AggregatorServer) {
	// If the following call panics, it indicates UnimplementedAggregatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Aggregator_ServiceDesc, srv)
}

func _Aggregator_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregatorServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Aggregator_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregatorServer).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Aggregator_ServiceDesc is the grpc.ServiceDesc for Aggregator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Aggregator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openindex.v1.Aggregator",
	HandlerType: (*AggregatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Aggregator_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/openindex.proto",
}

const (
	Root_Search_FullMethodName = "/openindex.v1.Root/Search"
)

// RootClient is the client API for Root service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RootClient interface {
	Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error)
}

type rootClient struct {
	cc grpc.ClientConnInterface
}

func NewRootClient(cc grpc.ClientConnInterface) RootClient {
	return &rootClient{cc}
}

func (c *rootClient) Search(ctx context.Context, in *SearchReq, opts ...grpc.CallOption) (*SearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResp)
	err := c.cc.Invoke(ctx, Root_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RootServer is the server API for Root service.
// All implementations must embed UnimplementedRootServer
// for forward compatibility.
type RootServer interface {
	Search(context.Context, *SearchReq) (*SearchResp, error)
	mustEmbedUnimplementedRootServer()
}

// UnimplementedRootServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRootServer struct{}

func (UnimplementedRootServer) Search(context.Context, *SearchReq) (*SearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedRootServer) mustEmbedUnimplementedRootServer() {}
func (UnimplementedRootServer) testEmbeddedByValue()              {}

// UnsafeRootServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RootServer will
// result in compilation errors.
type UnsafeRootServer interface {
	mustEmbedUnimplementedRootServer()
}

func RegisterRootServer(s grpc.ServiceRegistrar, srv RootServer) {
	// If the following call panics, it indicates UnimplementedRootServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Root_ServiceDesc, srv)
}

func _Root_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RootServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Root_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RootServer).Search(ctx, req.(*SearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Root_ServiceDesc is the grpc.ServiceDesc for Root service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Root_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openindex.v1.Root",
	HandlerType: (*RootServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Root_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/openindex.proto",
}

const (
	Snippets_Snippet_FullMethodName = "/openindex.v1.Snippets/Snippet"
)

// SnippetsClient is the client API for Snippets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnippetsClient interface {
	Snippet(ctx context.Context, in *SnippetReq, opts ...grpc.CallOption) (*SnippetResp, error)
}

type snippetsClient struct {
	cc grpc.ClientConnInterface
}

func NewSnippetsClient(cc grpc.ClientConnInterface) SnippetsClient {
	return &snippetsClient{cc}
}

func (c *snippetsClient) Snippet(ctx context.Context, in *SnippetReq, opts ...grpc.CallOption) (*SnippetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnippetResp)
	err := c.cc.Invoke(ctx, Snippets_Snippet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnippetsServer is the server API for Snippets service.
// All implementations must embed UnimplementedSnippetsServer
// for forward compatibility.
type SnippetsServer interface {
	Snippet(context.Context, *SnippetReq) (*SnippetResp, error)
	mustEmbedUnimplementedSnippetsServer()
}

// UnimplementedSnippetsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnippetsServer struct{}

func (UnimplementedSnippetsServer) Snippet(context.Context, *SnippetReq) (*SnippetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Snippet not implemented")
}
func (UnimplementedSnippetsServer) mustEmbedUnimplementedSnippetsServer() {}
func (UnimplementedSnippetsServer) testEmbeddedByValue()                  {}

// UnsafeSnippetsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnippetsServer will
// result in compilation errors.
type UnsafeSnippetsServer interface {
	mustEmbedUnimplementedSnippetsServer()
}

func RegisterSnippetsServer(s grpc.ServiceRegistrar, srv SnippetsServer) {
	// If the following call panics, it indicates UnimplementedSnippetsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Snippets_ServiceDesc, srv)
}

func _Snippets_Snippet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnippetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnippetsServer).Snippet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Snippets_Snippet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnippetsServer).Snippet(ctx, req.(*SnippetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Snippets_ServiceDesc is the grpc.ServiceDesc for Snippets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Snippets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openindex.v1.Snippets",
	HandlerType: (*SnippetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Snippet",
			Handler:    _Snippets_Snippet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/openindex.proto",
}

const (
	Embed_Embed_FullMethodName = "/openindex.v1.Embed/Embed"
)

// EmbedClient is the client API for Embed service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbedClient interface {
	Embed(ctx context.Context, in *EmbedReq, opts ...grpc.CallOption) (*EmbedResp, error)
}

type embedClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbedClient(cc grpc.ClientConnInterface) EmbedClient {
	return &embedClient{cc}
}

func (c *embedClient) Embed(ctx context.Context, in *EmbedReq, opts ...grpc.CallOption) (*EmbedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResp)
	err := c.cc.Invoke(ctx, Embed_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbedServer is the server API for Embed service.
// All implementations must embed UnimplementedEmbedServer
// for forward compatibility.
type EmbedServer interface {
	Embed(context.Context, *EmbedReq) (*EmbedResp, error)
	mustEmbedUnimplementedEmbedServer()
}

// UnimplementedEmbedServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmbedServer struct{}

func (UnimplementedEmbedServer) Embed(context.Context, *EmbedReq) (*EmbedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedEmbedServer) mustEmbedUnimplementedEmbedServer() {}
func (UnimplementedEmbedServer) testEmbeddedByValue()               {}

// UnsafeEmbedServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbedServer will
// result in compilation errors.
type UnsafeEmbedServer interface {
	mustEmbedUnimplementedEmbedServer()
}

func RegisterEmbedServer(s grpc.ServiceRegistrar, srv EmbedServer) {
	// If the following call panics, it indicates UnimplementedEmbedServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Embed_ServiceDesc, srv)
}

func _Embed_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbedServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Embed_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbedServer).Embed(ctx, req.(*EmbedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Embed_ServiceDesc is the grpc.ServiceDesc for Embed service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Embed_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openindex.v1.Embed",
	HandlerType: (*EmbedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _Embed_Embed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/openindex.proto",
}

const (
	Synthesize_Answer_FullMethodName = "/openindex.v1.Synthesize/Answer"
)

// SynthesizeClient is the client API for Synthesize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SynthesizeClient interface {
	Answer(ctx context.Context, in *AnswerReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnswerChunk], error)
}

type synthesizeClient struct {
	cc grpc.ClientConnInterface
}

func NewSynthesizeClient(cc grpc.ClientConnInterface) SynthesizeClient {
	return &synthesizeClient{cc}
}

func (c *synthesizeClient) Answer(ctx context.Context, in *AnswerReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnswerChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Synthesize_ServiceDesc.Streams[0], Synthesize_Answer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnswerReq, AnswerChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Synthesize_AnswerClient = grpc.ServerStreamingClient[AnswerChunk]

// SynthesizeServer is the server API for Synthesize service.
// All implementations must embed UnimplementedSynthesizeServer
// for forward compatibility.
type SynthesizeServer interface {
	Answer(*AnswerReq, grpc.ServerStreamingServer[AnswerChunk]) error
	mustEmbedUnimplementedSynthesizeServer()
}

// UnimplementedSynthesizeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSynthesizeServer struct{}

func (UnimplementedSynthesizeServer) Answer(*AnswerReq, grpc.ServerStreamingServer[AnswerChunk]) error {
	return status.Error(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedSynthesizeServer) mustEmbedUnimplementedSynthesizeServer() {}
func (UnimplementedSynthesizeServer) testEmbeddedByValue()                    {}

// UnsafeSynthesizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SynthesizeServer will
// result in compilation errors.
type UnsafeSynthesizeServer interface {
	mustEmbedUnimplementedSynthesizeServer()
}

func RegisterSynthesizeServer(s grpc.ServiceRegistrar, srv SynthesizeServer) {
	// If the following call panics, it indicates UnimplementedSynthesizeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Synthesize_ServiceDesc, srv)
}

func _Synthesize_Answer_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnswerReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SynthesizeServer).Answer(m, &grpc.GenericServerStream[AnswerReq, AnswerChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Synthesize_AnswerServer = grpc.ServerStreamingServer[AnswerChunk]

// Synthesize_ServiceDesc is the grpc.ServiceDesc for Synthesize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Synthesize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openindex.v1.Synthesize",
	HandlerType: (*SynthesizeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Answer",
			Handler:       _Synthesize_Answer_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/openindex.proto",
}

const (
	Indexer_Push_FullMethodName = "/openindex.v1.Indexer/Push"
)

// IndexerClient is the client API for Indexer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexerClient interface {
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocBatch, PushAck], error)
}

type indexerClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexerClient(cc grpc.ClientConnInterface) IndexerClient {
	return &indexerClient{cc}
}

func (c *indexerClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DocBatch, PushAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Indexer_ServiceDesc.Streams[0], Indexer_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DocBatch, PushAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Indexer_PushClient = grpc.ClientStreamingClient[DocBatch, PushAck]

// IndexerServer is the server API for Indexer service.
// All implementations must embed UnimplementedIndexerServer
// for forward compatibility.
type IndexerServer interface {
	Push(grpc.ClientStreamingServer[DocBatch, PushAck]) error
	mustEmbedUnimplementedIndexerServer()
}

// UnimplementedIndexerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexerServer struct{}

func (UnimplementedIndexerServer) Push(grpc.ClientStreamingServer[DocBatch, PushAck]) error {
	return status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedIndexerServer) mustEmbedUnimplementedIndexerServer() {}
func (UnimplementedIndexerServer) testEmbeddedByValue()                 {}

// UnsafeIndexerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexerServer will
// result in compilation errors.
type UnsafeIndexerServer interface {
	mustEmbedUnimplementedIndexerServer()
}

func RegisterIndexerServer(s grpc.ServiceRegistrar, srv IndexerServer) {
	// If the following call panics, it indicates UnimplementedIndexerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Indexer_ServiceDesc, srv)
}

func _Indexer_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexerServer).Push(&grpc.GenericServerStream[DocBatch, PushAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Indexer_PushServer = grpc.ClientStreamingServer[DocBatch, PushAck]

// Indexer_ServiceDesc is the grpc.ServiceDesc for Indexer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Indexer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openindex.v1.Indexer",
	HandlerType: (*IndexerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _Indexer_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/openindex.proto",
}

const (
	Control_Watch_FullMethodName = "/openindex.v1.Control/Watch"
)

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlClient interface {
	Watch(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClusterState], error)
}

type controlClient struct {
	cc grpc.ClientConnInterface
}

func NewControlClient(cc grpc.ClientConnInterface) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) Watch(ctx context.Context, in *WatchReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClusterState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Control_ServiceDesc.Streams[0], Control_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchReq, ClusterState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_WatchClient = grpc.ServerStreamingClient[ClusterState]

// ControlServer is the server API for Control service.
// All implementations must embed UnimplementedControlServer
// for forward compatibility.
type ControlServer interface {
	Watch(*WatchReq, grpc.ServerStreamingServer[ClusterState]) error
	mustEmbedUnimplementedControlServer()
}

// UnimplementedControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlServer struct{}

func (UnimplementedControlServer) Watch(*WatchReq, grpc.ServerStreamingServer[ClusterState]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedControlServer) mustEmbedUnimplementedControlServer() {}
func (UnimplementedControlServer) testEmbeddedByValue()                 {}

// UnsafeControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlServer will
// result in compilation errors.
type UnsafeControlServer interface {
	mustEmbedUnimplementedControlServer()
}

func RegisterControlServer(s grpc.ServiceRegistrar, srv ControlServer) {
	// If the following call panics, it indicates UnimplementedControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Control_ServiceDesc, srv)
}

func _Control_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlServer).Watch(m, &grpc.GenericServerStream[WatchReq, ClusterState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Control_WatchServer = grpc.ServerStreamingServer[ClusterState]

// Control_ServiceDesc is the grpc.ServiceDesc for Control service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Control_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "openindex.v1.Control",
	HandlerType: (*ControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Control_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/openindex.proto",
}
