// The OpenIndex internal data plane. Every inter-process call in the engine is
// a gRPC method defined here; this file is the single source of truth for the
// wire format (impl spec 02.4). Domain logic converts these messages to the
// Go types it owns at its package edge — these types do not travel deep into
// scoring or merge code (impl spec 02.6).
//
// Compatibility rule: fields are added, never renumbered or repurposed; removed
// fields are reserved. The snapshot id and codec version travel in the request
// so a leaf can reject a format it cannot read instead of misreading it.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/openindex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchReq is the query as it enters the serving tree and is fanned out
// unchanged to every aggregator.
type SearchReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Query string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK  uint32                 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	// snapshot pins the index version this query must be answered from; a leaf
	// holding a different snapshot rejects rather than mixing results.
	Snapshot string `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// deadline_unix_nanos is the absolute edge deadline. Every hop inherits the
	// remaining budget rather than starting a fresh timeout (impl spec 01.2).
	DeadlineUnixNanos int64 `protobuf:"varint,4,opt,name=deadline_unix_nanos,json=deadlineUnixNanos,proto3" json:"deadline_unix_nanos,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchReq) Reset() {
	*x = SearchReq{}
	mi := &file_proto_openindex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReq) ProtoMessage() {}

func (x *SearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReq.ProtoReflect.Descriptor instead.
func (*SearchReq) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{0}
}

func (x *SearchReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchReq) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchReq) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *SearchReq) GetDeadlineUnixNanos() int64 {
	if x != nil {
		return x.DeadlineUnixNanos
	}
	return 0
}

// SearchShardReq is the per-leaf request. It is a SearchReq plus the shard the
// leaf must restrict to, so one aggregator can address many shards on one host.
type SearchShardReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           *SearchReq             `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Shard         uint32                 `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchShardReq) Reset() {
	*x = SearchShardReq{}
	mi := &file_proto_openindex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchShardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchShardReq) ProtoMessage() {}

func (x *SearchShardReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchShardReq.ProtoReflect.Descriptor instead.
func (*SearchShardReq) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{1}
}

func (x *SearchShardReq) GetReq() *SearchReq {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *SearchShardReq) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

// ScoredDoc is one hit. doc_id is segment-local and valid only for this query;
// url and content_hash are the durable external identity (impl spec 02.4).
type ScoredDoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segment       uint64                 `protobuf:"varint,1,opt,name=segment,proto3" json:"segment,omitempty"`
	DocId         uint32                 `protobuf:"varint,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ContentHash   []byte                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredDoc) Reset() {
	*x = ScoredDoc{}
	mi := &file_proto_openindex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredDoc) ProtoMessage() {}

func (x *ScoredDoc) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredDoc.ProtoReflect.Descriptor instead.
func (*ScoredDoc) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{2}
}

func (x *ScoredDoc) GetSegment() uint64 {
	if x != nil {
		return x.Segment
	}
	return 0
}

func (x *ScoredDoc) GetDocId() uint32 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *ScoredDoc) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoredDoc) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScoredDoc) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

type SearchShardResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hits  []*ScoredDoc           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	// total_matched is the shard's match count before top-k truncation, summed
	// up the tree into an estimated result count.
	TotalMatched  uint64 `protobuf:"varint,2,opt,name=total_matched,json=totalMatched,proto3" json:"total_matched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchShardResp) Reset() {
	*x = SearchShardResp{}
	mi := &file_proto_openindex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchShardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchShardResp) ProtoMessage() {}

func (x *SearchShardResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchShardResp.ProtoReflect.Descriptor instead.
func (*SearchShardResp) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{3}
}

func (x *SearchShardResp) GetHits() []*ScoredDoc {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchShardResp) GetTotalMatched() uint64 {
	if x != nil {
		return x.TotalMatched
	}
	return 0
}

type SearchResp struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Hits         []*ScoredDoc           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	TotalMatched uint64                 `protobuf:"varint,2,opt,name=total_matched,json=totalMatched,proto3" json:"total_matched,omitempty"`
	// partial is set when the cutoff fired before every shard answered; the
	// result is usable but not exhaustive (impl spec 08 good-enough cutoff).
	Partial       bool `protobuf:"varint,3,opt,name=partial,proto3" json:"partial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResp) Reset() {
	*x = SearchResp{}
	mi := &file_proto_openindex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResp) ProtoMessage() {}

func (x *SearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResp.ProtoReflect.Descriptor instead.
func (*SearchResp) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResp) GetHits() []*ScoredDoc {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchResp) GetTotalMatched() uint64 {
	if x != nil {
		return x.TotalMatched
	}
	return 0
}

func (x *SearchResp) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

type SnippetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Docs          []*ScoredDoc           `protobuf:"bytes,2,rep,name=docs,proto3" json:"docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnippetReq) Reset() {
	*x = SnippetReq{}
	mi := &file_proto_openindex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnippetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnippetReq) ProtoMessage() {}

func (x *SnippetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnippetReq.ProtoReflect.Descriptor instead.
func (*SnippetReq) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{5}
}

func (x *SnippetReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SnippetReq) GetDocs() []*ScoredDoc {
	if x != nil {
		return x.Docs
	}
	return nil
}

type Snippet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segment       uint64                 `protobuf:"varint,1,opt,name=segment,proto3" json:"segment,omitempty"`
	DocId         uint32                 `protobuf:"varint,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snippet) Reset() {
	*x = Snippet{}
	mi := &file_proto_openindex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snippet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snippet) ProtoMessage() {}

func (x *Snippet) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snippet.ProtoReflect.Descriptor instead.
func (*Snippet) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{6}
}

func (x *Snippet) GetSegment() uint64 {
	if x != nil {
		return x.Segment
	}
	return 0
}

func (x *Snippet) GetDocId() uint32 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *Snippet) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Snippet) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SnippetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snippets      []*Snippet             `protobuf:"bytes,1,rep,name=snippets,proto3" json:"snippets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnippetResp) Reset() {
	*x = SnippetResp{}
	mi := &file_proto_openindex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnippetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnippetResp) ProtoMessage() {}

func (x *SnippetResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnippetResp.ProtoReflect.Descriptor instead.
func (*SnippetResp) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{7}
}

func (x *SnippetResp) GetSnippets() []*Snippet {
	if x != nil {
		return x.Snippets
	}
	return nil
}

type EmbedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedReq) Reset() {
	*x = EmbedReq{}
	mi := &file_proto_openindex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedReq) ProtoMessage() {}

func (x *EmbedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedReq.ProtoReflect.Descriptor instead.
func (*EmbedReq) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{8}
}

func (x *EmbedReq) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_proto_openindex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{9}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type EmbedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vectors       []*Vector              `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResp) Reset() {
	*x = EmbedResp{}
	mi := &file_proto_openindex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResp) ProtoMessage() {}

func (x *EmbedResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResp.ProtoReflect.Descriptor instead.
func (*EmbedResp) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{10}
}

func (x *EmbedResp) GetVectors() []*Vector {
	if x != nil {
		return x.Vectors
	}
	return nil
}

type AnswerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Context       []*Snippet             `protobuf:"bytes,2,rep,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerReq) Reset() {
	*x = AnswerReq{}
	mi := &file_proto_openindex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerReq) ProtoMessage() {}

func (x *AnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerReq.ProtoReflect.Descriptor instead.
func (*AnswerReq) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{11}
}

func (x *AnswerReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AnswerReq) GetContext() []*Snippet {
	if x != nil {
		return x.Context
	}
	return nil
}

// GroundingSupport ties a span of the generated answer to the source chunk that
// supports it (impl spec 09 grounding data model).
type GroundingSupport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"` // character offset into the answer text
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	ChunkIndex    uint32                 `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"` // index into AnswerReq.context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroundingSupport) Reset() {
	*x = GroundingSupport{}
	mi := &file_proto_openindex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroundingSupport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroundingSupport) ProtoMessage() {}

func (x *GroundingSupport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroundingSupport.ProtoReflect.Descriptor instead.
func (*GroundingSupport) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{12}
}

func (x *GroundingSupport) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GroundingSupport) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *GroundingSupport) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type AnswerChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Supports      []*GroundingSupport    `protobuf:"bytes,2,rep,name=supports,proto3" json:"supports,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerChunk) Reset() {
	*x = AnswerChunk{}
	mi := &file_proto_openindex_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerChunk) ProtoMessage() {}

func (x *AnswerChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerChunk.ProtoReflect.Descriptor instead.
func (*AnswerChunk) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{13}
}

func (x *AnswerChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AnswerChunk) GetSupports() []*GroundingSupport {
	if x != nil {
		return x.Supports
	}
	return nil
}

func (x *AnswerChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type Document struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Url              string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ContentHash      []byte                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body             string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	FetchedUnixNanos int64                  `protobuf:"varint,5,opt,name=fetched_unix_nanos,json=fetchedUnixNanos,proto3" json:"fetched_unix_nanos,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_openindex_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{14}
}

func (x *Document) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Document) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Document) GetFetchedUnixNanos() int64 {
	if x != nil {
		return x.FetchedUnixNanos
	}
	return 0
}

type DocBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          []*Document            `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocBatch) Reset() {
	*x = DocBatch{}
	mi := &file_proto_openindex_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocBatch) ProtoMessage() {}

func (x *DocBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocBatch.ProtoReflect.Descriptor instead.
func (*DocBatch) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{15}
}

func (x *DocBatch) GetDocs() []*Document {
	if x != nil {
		return x.Docs
	}
	return nil
}

type PushAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Segment       string                 `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushAck) Reset() {
	*x = PushAck{}
	mi := &file_proto_openindex_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushAck) ProtoMessage() {}

func (x *PushAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushAck.ProtoReflect.Descriptor instead.
func (*PushAck) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{16}
}

func (x *PushAck) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *PushAck) GetSegment() string {
	if x != nil {
		return x.Segment
	}
	return ""
}

type WatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchReq) Reset() {
	*x = WatchReq{}
	mi := &file_proto_openindex_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchReq) ProtoMessage() {}

func (x *WatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchReq.ProtoReflect.Descriptor instead.
func (*WatchReq) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{17}
}

func (x *WatchReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ShardAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shard         uint32                 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Replicas      []string               `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"` // host:port of each replica serving the shard
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardAssignment) Reset() {
	*x = ShardAssignment{}
	mi := &file_proto_openindex_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardAssignment) ProtoMessage() {}

func (x *ShardAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardAssignment.ProtoReflect.Descriptor instead.
func (*ShardAssignment) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{18}
}

func (x *ShardAssignment) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *ShardAssignment) GetReplicas() []string {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type ClusterState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      string                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Shards        []*ShardAssignment     `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterState) Reset() {
	*x = ClusterState{}
	mi := &file_proto_openindex_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterState) ProtoMessage() {}

func (x *ClusterState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_openindex_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterState.ProtoReflect.Descriptor instead.
func (*ClusterState) Descriptor() ([]byte, []int) {
	return file_proto_openindex_proto_rawDescGZIP(), []int{19}
}

func (x *ClusterState) GetSnapshot() string {
	if x != nil {
		return x.Snapshot
	}
	return ""
}

func (x *ClusterState) GetShards() []*ShardAssignment {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *ClusterState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_openindex_proto protoreflect.FileDescriptor

const file_proto_openindex_proto_rawDesc = "" +
	"\n" +
	"\x15proto/openindex.proto\x12\fopenindex.v1\"\x82\x01\n" +
	"\tSearchReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\rR\x04topK\x12\x1a\n" +
	"\bsnapshot\x18\x03 \x01(\tR\bsnapshot\x12.\n" +
	"\x13deadline_unix_nanos\x18\x04 \x01(\x03R\x11deadlineUnixNanos\"Q\n" +
	"\x0eSearchShardReq\x12)\n" +
	"\x03req\x18\x01 \x01(\v2\x17.openindex.v1.SearchReqR\x03req\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\rR\x05shard\"\x87\x01\n" +
	"\tScoredDoc\x12\x18\n" +
	"\asegment\x18\x01 \x01(\x04R\asegment\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\rR\x05docId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\fR\vcontentHash\"c\n" +
	"\x0fSearchShardResp\x12+\n" +
	"\x04hits\x18\x01 \x03(\v2\x17.openindex.v1.ScoredDocR\x04hits\x12#\n" +
	"\rtotal_matched\x18\x02 \x01(\x04R\ftotalMatched\"x\n" +
	"\n" +
	"SearchResp\x12+\n" +
	"\x04hits\x18\x01 \x03(\v2\x17.openindex.v1.ScoredDocR\x04hits\x12#\n" +
	"\rtotal_matched\x18\x02 \x01(\x04R\ftotalMatched\x12\x18\n" +
	"\apartial\x18\x03 \x01(\bR\apartial\"O\n" +
	"\n" +
	"SnippetReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12+\n" +
	"\x04docs\x18\x02 \x03(\v2\x17.openindex.v1.ScoredDocR\x04docs\"d\n" +
	"\aSnippet\x12\x18\n" +
	"\asegment\x18\x01 \x01(\x04R\asegment\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\rR\x05docId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"@\n" +
	"\vSnippetResp\x121\n" +
	"\bsnippets\x18\x01 \x03(\v2\x15.openindex.v1.SnippetR\bsnippets\" \n" +
	"\bEmbedReq\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\" \n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\";\n" +
	"\tEmbedResp\x12.\n" +
	"\avectors\x18\x01 \x03(\v2\x14.openindex.v1.VectorR\avectors\"R\n" +
	"\tAnswerReq\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12/\n" +
	"\acontext\x18\x02 \x03(\v2\x15.openindex.v1.SnippetR\acontext\"[\n" +
	"\x10GroundingSupport\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\rR\n" +
	"chunkIndex\"q\n" +
	"\vAnswerChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12:\n" +
	"\bsupports\x18\x02 \x03(\v2\x1e.openindex.v1.GroundingSupportR\bsupports\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"\x97\x01\n" +
	"\bDocument\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\fR\vcontentHash\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12,\n" +
	"\x12fetched_unix_nanos\x18\x05 \x01(\x03R\x10fetchedUnixNanos\"6\n" +
	"\bDocBatch\x12*\n" +
	"\x04docs\x18\x01 \x03(\v2\x16.openindex.v1.DocumentR\x04docs\"?\n" +
	"\aPushAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\x12\x18\n" +
	"\asegment\x18\x02 \x01(\tR\asegment\"\x1e\n" +
	"\bWatchReq\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\"C\n" +
	"\x0fShardAssignment\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\rR\x05shard\x12\x1a\n" +
	"\breplicas\x18\x02 \x03(\tR\breplicas\"{\n" +
	"\fClusterState\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\tR\bsnapshot\x125\n" +
	"\x06shards\x18\x02 \x03(\v2\x1d.openindex.v1.ShardAssignmentR\x06shards\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion2M\n" +
	"\x04Leaf\x12E\n" +
	"\x06Search\x12\x1c.openindex.v1.SearchShardReq\x1a\x1d.openindex.v1.SearchShardResp2I\n" +
	"\n" +
	"Aggregator\x12;\n" +
	"\x06Search\x12\x17.openindex.v1.SearchReq\x1a\x18.openindex.v1.SearchResp2C\n" +
	"\x04Root\x12;\n" +
	"\x06Search\x12\x17.openindex.v1.SearchReq\x1a\x18.openindex.v1.SearchResp2J\n" +
	"\bSnippets\x12>\n" +
	"\aSnippet\x12\x18.openindex.v1.SnippetReq\x1a\x19.openindex.v1.SnippetResp2A\n" +
	"\x05Embed\x128\n" +
	"\x05Embed\x12\x16.openindex.v1.EmbedReq\x1a\x17.openindex.v1.EmbedResp2L\n" +
	"\n" +
	"Synthesize\x12>\n" +
	"\x06Answer\x12\x17.openindex.v1.AnswerReq\x1a\x19.openindex.v1.AnswerChunk0\x012B\n" +
	"\aIndexer\x127\n" +
	"\x04Push\x12\x16.openindex.v1.DocBatch\x1a\x15.openindex.v1.PushAck(\x012H\n" +
	"\aControl\x12=\n" +
	"\x05Watch\x12\x16.openindex.v1.WatchReq\x1a\x1a.openindex.v1.ClusterState0\x01B\x17Z\x15openindex/proto;protob\x06proto3"

var (
	file_proto_openindex_proto_rawDescOnce sync.Once
	file_proto_openindex_proto_rawDescData []byte
)

func file_proto_openindex_proto_rawDescGZIP() []byte {
	file_proto_openindex_proto_rawDescOnce.Do(func() {
		file_proto_openindex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_openindex_proto_rawDesc), len(file_proto_openindex_proto_rawDesc)))
	})
	return file_proto_openindex_proto_rawDescData
}

var file_proto_openindex_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_openindex_proto_goTypes = []any{
	(*SearchReq)(nil),        // 0: openindex.v1.SearchReq
	(*SearchShardReq)(nil),   // 1: openindex.v1.SearchShardReq
	(*ScoredDoc)(nil),        // 2: openindex.v1.ScoredDoc
	(*SearchShardResp)(nil),  // 3: openindex.v1.SearchShardResp
	(*SearchResp)(nil),       // 4: openindex.v1.SearchResp
	(*SnippetReq)(nil),       // 5: openindex.v1.SnippetReq
	(*Snippet)(nil),          // 6: openindex.v1.Snippet
	(*SnippetResp)(nil),      // 7: openindex.v1.SnippetResp
	(*EmbedReq)(nil),         // 8: openindex.v1.EmbedReq
	(*Vector)(nil),           // 9: openindex.v1.Vector
	(*EmbedResp)(nil),        // 10: openindex.v1.EmbedResp
	(*AnswerReq)(nil),        // 11: openindex.v1.AnswerReq
	(*GroundingSupport)(nil), // 12: openindex.v1.GroundingSupport
	(*AnswerChunk)(nil),      // 13: openindex.v1.AnswerChunk
	(*Document)(nil),         // 14: openindex.v1.Document
	(*DocBatch)(nil),         // 15: openindex.v1.DocBatch
	(*PushAck)(nil),          // 16: openindex.v1.PushAck
	(*WatchReq)(nil),         // 17: openindex.v1.WatchReq
	(*ShardAssignment)(nil),  // 18: openindex.v1.ShardAssignment
	(*ClusterState)(nil),     // 19: openindex.v1.ClusterState
}
var file_proto_openindex_proto_depIdxs = []int32{
	0,  // 0: openindex.v1.SearchShardReq.req:type_name -> openindex.v1.SearchReq
	2,  // 1: openindex.v1.SearchShardResp.hits:type_name -> openindex.v1.ScoredDoc
	2,  // 2: openindex.v1.SearchResp.hits:type_name -> openindex.v1.ScoredDoc
	2,  // 3: openindex.v1.SnippetReq.docs:type_name -> openindex.v1.ScoredDoc
	6,  // 4: openindex.v1.SnippetResp.snippets:type_name -> openindex.v1.Snippet
	9,  // 5: openindex.v1.EmbedResp.vectors:type_name -> openindex.v1.Vector
	6,  // 6: openindex.v1.AnswerReq.context:type_name -> openindex.v1.Snippet
	12, // 7: openindex.v1.AnswerChunk.supports:type_name -> openindex.v1.GroundingSupport
	14, // 8: openindex.v1.DocBatch.docs:type_name -> openindex.v1.Document
	18, // 9: openindex.v1.ClusterState.shards:type_name -> openindex.v1.ShardAssignment
	1,  // 10: openindex.v1.Leaf.Search:input_type -> openindex.v1.SearchShardReq
	0,  // 11: openindex.v1.Aggregator.Search:input_type -> openindex.v1.SearchReq
	0,  // 12: openindex.v1.Root.Search:input_type -> openindex.v1.SearchReq
	5,  // 13: openindex.v1.Snippets.Snippet:input_type -> openindex.v1.SnippetReq
	8,  // 14: openindex.v1.Embed.Embed:input_type -> openindex.v1.EmbedReq
	11, // 15: openindex.v1.Synthesize.Answer:input_type -> openindex.v1.AnswerReq
	15, // 16: openindex.v1.Indexer.Push:input_type -> openindex.v1.DocBatch
	17, // 17: openindex.v1.Control.Watch:input_type -> openindex.v1.WatchReq
	3,  // 18: openindex.v1.Leaf.Search:output_type -> openindex.v1.SearchShardResp
	4,  // 19: openindex.v1.Aggregator.Search:output_type -> openindex.v1.SearchResp
	4,  // 20: openindex.v1.Root.Search:output_type -> openindex.v1.SearchResp
	7,  // 21: openindex.v1.Snippets.Snippet:output_type -> openindex.v1.SnippetResp
	10, // 22: openindex.v1.Embed.Embed:output_type -> openindex.v1.EmbedResp
	13, // 23: openindex.v1.Synthesize.Answer:output_type -> openindex.v1.AnswerChunk
	16, // 24: openindex.v1.Indexer.Push:output_type -> openindex.v1.PushAck
	19, // 25: openindex.v1.Control.Watch:output_type -> openindex.v1.ClusterState
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_openindex_proto_init() }
func file_proto_openindex_proto_init() {
	if File_proto_openindex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_openindex_proto_rawDesc), len(file_proto_openindex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   8,
		},
		GoTypes:           file_proto_openindex_proto_goTypes,
		DependencyIndexes: file_proto_openindex_proto_depIdxs,
		MessageInfos:      file_proto_openindex_proto_msgTypes,
	}.Build()
	File_proto_openindex_proto = out.File
	file_proto_openindex_proto_goTypes = nil
	file_proto_openindex_proto_depIdxs = nil
}
